# Generated by Django 6.0.3 on 2026-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinguinAPI', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
